apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
spec:
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MONGO_INITDB_ROOT_USERNAME
        - name : ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER  
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: ME_CONFIG_MONGODB_SERVER  
      nodeSelector:
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpresssvc
spec:
  selector:
    app: mongoexpress
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer

        
